---
- name: clone dotfiles
  git:
    repo: https://github.com/bob3000/dotfiles.git
    clone: true
    version: linux
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"

- name: link dotfiles
  shell: "[ -e {{ lookup('env', 'HOME') }}/.gitconfig ] || ./install.sh"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
    creates: "{{ lookup('env', 'HOME') }}/.gitconfig"

- name: install vim plug
  shell: >
    curl -fLo {{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim --create-dirs 
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"
