---
- name: install packages
  apt:
    update_cache: yes
    name:
      - build-essential
      - cmake
      - dnsutils
      - curl
      - golang
      - liquidprompt
      - neovim
      - unzip
      - wget
